<%@ Page Language="C#" AutoEventWireup="True" CodeBehind="UpdatePrices.aspx.cs" Inherits="OxxCommerceStarterKit.Web.Plugins.CommerceTools.Prices.UpdatePrices" %>

<%@ Register TagPrefix="EPiServerShell" Assembly="EPiServer.Shell" Namespace="EPiServer.Shell.Web.UI.WebControls" %>
<%@ Register TagPrefix="mc2" Namespace="Mediachase.BusinessFoundation" Assembly="Mediachase.BusinessFoundation, Version=7.0.243.0, Culture=neutral, PublicKeyToken=41d2e7a615ba286c" %>


<asp:content contentplaceholderid="FullRegion" runat="server">
     <script type="text/javascript">
         $(document).ready(function () {
             epi.shell.layout.initScrollableArea({ area: "#epi-application" });
         });

     </script>
    <link href="../static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../static/css/epioverride.css" rel="stylesheet" />    
    <link href="../static/css/bootstrap-datepicker3.css" rel="stylesheet" />
<link href="../static/css/bootstrap-timepicker.min.css" rel="stylesheet" />
    <div>
        <EPiServerShell:ShellMenu ID="ShellMenu2" runat="server" SelectionPath="/global/commercetools/priceupdate" Area="CommerceTools" />

        <div>
            <div id="epi-application">
                <div id="epi-applicationBody">                    
                        <div class="col-lg-6">
                            <div id="DataForm">
    <div class="setting-panel top-panel">
        <h1>Update local prices</h1>
        <div>
            Use this form to set local prices.
        </div>

        <asp:Panel runat="server" ID="ErrorPanel" CssClass="error">
            <div class="alert alert-danger" role="alert">
                <asp:Label runat="server" ID="ErrorMessage"></asp:Label>
            </div>
        </asp:Panel>
        
          <div class="form-group form-inline col-lg-12">              
              <input runat="server" type="text" placeholder="Code" class="form-control" ID="Code"/>      
        <asp:Button runat="server" OnClick="GetEntry_Click" CssClass="btn btn-default" Text="Search"/>
  </div>
        
        <div class="form-group col-lg-12">              
        
        
         <asp:Panel runat="server" ID="StylePanel" Visible="False">             
                        <fieldset>
                            <legend style="margin-left: 10px;"><b>Style</b></legend>
                            <div style="padding: 10px;">
                                <asp:Label runat="server" ID="StyleNameLabel" Text="Name:"></asp:Label>
                                <asp:Label runat="server" ID="StyleNameValue" CssClass="bold"></asp:Label>
                            </div>
                        </fieldset>
                    </asp:Panel>
                    <asp:Panel runat="server" ID="VariantPanel" Visible="False">
                        <fieldset>
                            <legend style="margin-left: 10px;"><b>Variants</b></legend>
                            <div style="padding: 10px;">
                                <asp:ListBox runat="server" Height="80" ID="VariantsList" DataTextField="DisplayText" BackColor="#E4E4E4" />
                            </div>
                        </fieldset>

                        <fieldset style="padding-right: 10px;">
                            <legend style="margin-left: 10px;"><b>Prices</b></legend>
                            <div style="padding: 10px;">
                                <div style="display: none">
                                    <asp:ListBox runat="server" ID="SkuList" DataTextField="Id" DataValueField="Id" />
                                </div>
                                <asp:GridView runat="server" ID="SkuPrices" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="SkuPrice_OnDeleting" CellPadding="5" BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px">
                                    <Columns>
                                        <asp:BoundField DataField="From" HeaderText="From" />
                                        <asp:BoundField DataField="To" HeaderText="To" />
                                        <asp:BoundField DataField="Value" HeaderText="Value">
                                            <ItemStyle Width="70px" HorizontalAlign="Right" />
                                        </asp:BoundField>
                                        <asp:BoundField DataField="Currency" HeaderText="">
                                            <ItemStyle Width="50px" HorizontalAlign="Center"></ItemStyle>
                                        </asp:BoundField>

                                        <asp:BoundField DataField="Type" HeaderText="Type">
                                            <ItemStyle Width="50px" HorizontalAlign="Center"></ItemStyle>
                                        </asp:BoundField>
                                        <asp:BoundField DataField="PriceCode" HeaderText="Price code" />
                                    </Columns>
                                    <EmptyDataTemplate>
                                        <span>No prices for current SKU</span>
                                    </EmptyDataTemplate>
                                    <HeaderStyle BackColor="#99CCFF" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" Font-Bold="True" Font-Size="Medium" HorizontalAlign="Center" />
                                    <RowStyle Height="25px" HorizontalAlign="Left" VerticalAlign="Middle" />
                                </asp:GridView>
                                <asp:Panel runat="server" ID="DeletePricePanel" Visible="False">
                                    <asp:HiddenField runat="server" ID="Price"></asp:HiddenField>
                                    <asp:HiddenField runat="server" ID="DeleteFromSkuId" />
                                    <asp:HiddenField runat="server" ID="DeleteValidFrom" />
                                    <asp:HiddenField runat="server" ID="DeleteValidTo" />
                                    <asp:HiddenField runat="server" ID="DeleteCurrency" />
                                    <asp:HiddenField runat="server" ID="DeleteType" />
                                    <asp:HiddenField runat="server" ID="DeleteValue" />
                                    <fieldset style="margin: 10px; padding: 10px;">
                                        <legend><b>Confirm delete?</b></legend>
                                        <span style="padding: 10px">

                                            <mc2:IMButton ID="CancelButton" runat="server" IsDecline="True" CausesValidation="True" OnServerClick="Cancel_Click" Text="Cancel">
                                            </mc2:IMButton>

                                        </span><span style="padding: 10px">
                                            <mc2:IMButton ID="ConfirmDeleteButton" runat="server" CausesValidation="True" ValidationGroup="Delete" OnServerClick="ConfirmDelete_Click" Text="Delete">
                                            </mc2:IMButton>
                                        </span>

                                    </fieldset>
                                </asp:Panel>
                            </div>
                        </fieldset>
                    </asp:Panel>
            </div>
        <div class="form-horizontal">
        <div class="form-group">
            <strong>Add new local price</strong>
        </div>
              <div class="form-group form-inline">
                  <asp:Label runat="server" AssociatedControlID="StartDate" CssClass="col-sm-2 control-label" Text="From date:"></asp:Label>
   
    <div class="form-inline">
        <input type="text" runat="server" class="form-control" ID="StartDate"/>    

                   
            <input id="startTime" runat="server" type="text" class="form-control timepicker">
           
        </div>
  
  </div>
            
               <div class="form-group">
                  <asp:Label runat="server" AssociatedControlID="EndDate" CssClass="col-sm-2 control-label" Text="To date:"></asp:Label>
   
    <div class="form-inline">  
        <input type="text" runat="server" class="form-control" ID="EndDate"/>    
          <input id="endTime" runat="server" type="text" class="form-control timepicker">
    </div>
  
  </div>
             <div class="form-group">
                  <asp:Label runat="server" AssociatedControlID="Market" CssClass="col-sm-2 control-label" Text="Market:"></asp:Label>
   
    <div class="">  
         <asp:ListBox runat="server" ID="Market" DataValueField="MarketId" DataTextField="DisplayText" OnSelectedIndexChanged="Market_SelectedChanged" AutoPostBack="True" />
    </div>


  
  </div>


                <div class="form-group">
                  <asp:Label runat="server" AssociatedControlID="PriceType" CssClass="col-sm-2 control-label" Text="Price type/code:"></asp:Label>   
    <div class="form-inline">  
           <asp:DropDownList runat="server" ID="PriceType" CssClass="form-control" />
                    <asp:TextBox runat="server" ID="PriceCode"></asp:TextBox>
    </div>
  </div>

                        <div class="form-group">
                  <asp:Label runat="server" AssociatedControlID="Value" CssClass="col-sm-2 control-label" Text="Value:"></asp:Label>   
    <div class="">  
          <asp:TextBox runat="server" ID="Value"></asp:TextBox>
                    <asp:Literal runat="server" ID="SelectedCurrency"></asp:Literal>
    </div>
  </div>

            <div class="form-group">
                  
    <div class="">  
        
                    <asp:Button ID="SetPriceButton" runat="server" CssClass="btn btn-default" OnClick="SetPrice_Click" Text="Add price">
                    </asp:Button>
    </div>
  </div>

        </div>
        

      
    </div>



</div>
                            <br /><br /><br /><br />
                            </div>                        
                    </div>
                </div>
            </div>
        </div>
    <div>
     
<script src="../static/scripts/jquery-1.9.0.js"></script>
        
        <script src="../static/scripts/jquery.simple-dtpicker.js"></script>        
        <script src="../static/scripts/bootstrap.min.js"></script>
        <script src="../static/scripts/bootstrap-datepicker.js"></script>
        <script src="../static/scripts/bootstrap-timepicker.min.js"></script>
<script src="../static/scripts/priceplugin.js"></script>




       
    </div>
</asp:content>

